# Generated by Django 4.2 on 2023-05-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='memo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='memo.tag'),
        ),
    ]
