# Generated by Django 4.2 on 2023-06-05 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0004_memo_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='title',
        ),
    ]
