# Generated by Django 4.2 on 2023-04-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='sell_items/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='sell_items/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='sell_items/')),
                ('photo1_thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('photo2_thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('photo3_thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
            ],
        ),
    ]
