# Generated by Django 4.2 on 2023-04-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybookmark', '0002_bookmark_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='category',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
