# Generated by Django 4.2 on 2023-04-26 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybookmark', '0003_remove_bookmark_category_bookmark_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='user',
            new_name='owner',
        ),
    ]
