# Generated by Django 4.2 on 2023-06-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, default='default_icon.png', upload_to='profile_icons/'),
        ),
    ]
