# Generated by Django 4.2 on 2023-06-13 12:58

from django.db import migrations

def set_default_icon(apps, schema_editor):
    User = apps.get_model('myapp', 'CustomUser')
    for user in User.objects.filter(icon=''):
        user.icon = 'images/default_icon.png'
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_customuser_icon'),
    ]

    operations = [
        migrations.RunPython(set_default_icon),
    ]
