# Generated by Django 4.2 on 2023-06-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20230613_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, default='images/default_icon.png', null=True, upload_to='profile_icons/'),
        ),
    ]
