# Generated by Django 4.2 on 2023-06-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_tag_movie_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='comments',
        ),
    ]
