# Generated by Django 4.2 on 2023-04-17 23:20

from django.db import migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
