# Generated by Django 4.2 on 2023-06-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_photo_secrets'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='range',
            field=models.IntegerField(blank=True, choices=[(50, '50m'), (100, '100m'), (1000, '1km'), (10000, '10km'), (100000, '100km')], null=True),
        ),
    ]
